export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const UPDATE_EXPENSES = 'UPDATE_EXPENSES';
export const SET_EXPENSES = 'SET_EXPENSES';
export const EXPENSES_API_CALL_FAILED = 'EXPENSES_API_CALL_FAILED'

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const CATEGORIES_API_CALL_FAILED = 'CATEGORIES_API_CALL_FAILED'

export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_PHOTO = 'SET_USER_PHOTO';
export const USER_API_CALL_FAILED = 'USER_API_CALL_FAILED';
